version: '3.8'

services:
  backend:
    build: .
    ports:
      - "5678:5678"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    command: npm start 
